In [1]:
import glob


import numpy as np
import pandas as pd

import networkx as nx
from matplotlib import pyplot as plt

from scipy.sparse import diags
from scipy.sparse.linalg import cg


from src.mwnetwork.clustering import load_core_graph
from utils.path import find_root

/anaconda3/envs/metaboenv/lib/python3.14/site-packages/sspa/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution

In [2]:
ROOT = find_root()
CORE_GRAPH_DIR = ROOT / "checkpoints" / "metabolomics_workbench" / "core_graph"
NAFLD_ANALYSIS_DIR = ROOT / "checkpoints" / "metabolomics_workbench" / "nafld_analysis"

In [3]:
study_files = sorted(glob.glob(str(NAFLD_ANALYSIS_DIR / "*.csv")))
study_files

['/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST000916_nafld_severity.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST000977_nafld_vs_healthy.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST001710_nafld_severity.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST001711_nafld_severity.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST001842_nafld_vs_healthy.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST001843_nafld_vs_healthy.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST001964_nafld_severity.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST002091_nafld_vs_healthy.csv',
 '/home/saldan/Desktop/projects/mw-metabolite-network/checkpoints/metabolomics_workbench/nafld_analysis/ST002269_nafld_vs_healthy.csv']

In [4]:
all_associations = pd.concat([
    pd.read_csv(f).dropna(subset=["kendall_tau"]).assign(study_id=f.split("/")[-1].split("_")[0]).set_index(["study_id", "refmet_id"])
    for f in study_files]
)
all_associations

                    kendall_tau   p_value    n
study_id refmet_id
ST000916 RM0001239    -0.106929  0.185349   88
         RM0001442    -0.165306  0.041830   87
         RM0001603     0.201491  0.012591   88
         RM0001619    -0.348049  0.000016   88
         RM0001782    -0.181874  0.024596   88
...                         ...       ...  ...
ST002269 RM0153846     0.155488  0.015631  165
         RM0154019     0.091550  0.209707  165
         RM0154093     0.081550  0.203134  165
         RM0154083     0.195892  0.002213  165
         RM0154023     0.028142  0.697953  165

[2092 rows x 3 columns]

In [5]:
def associations_purged_from(study_id):
    """
    Purge associations from a given study_id from the associations dataframe.
    """
    return all_associations.drop(study_id, level="study_id")

associations_purged_from("ST002269")

                    kendall_tau   p_value   n
study_id refmet_id
ST000916 RM0001239    -0.106929  0.185349  88
         RM0001442    -0.165306  0.041830  87
         RM0001603     0.201491  0.012591  88
         RM0001619    -0.348049  0.000016  88
         RM0001782    -0.181874  0.024596  88
...                         ...       ...  ..
ST002091 RM0071606     0.250780  0.029807  52
         RM0071607     0.237542  0.030957  57
         RM0055968    -0.005981  0.973808  22
         RM0056115     0.121306  0.195252  78
         RM0023722     0.102552  0.399467  47

[1750 rows x 3 columns]

In [6]:
def metabolite_association(refmet_id, associations=all_associations):
    """
    Calculate the overall association of a metabolite with its associated signals.
    """
    try:
        tau, n = associations.loc[(slice(None), refmet_id), ["kendall_tau", "n"]].values.T
        w = (n-4)/0.437
        z = np.arctanh(tau)
        z = (w*z).sum()/w.sum()
        return z
    except KeyError:
        return np.nan # metabolite not tested in any study in the associations dataframe

metabolite_association("RM0001239", associations=associations_purged_from("ST000916"))

np.float64(0.1502665376846832)

In [7]:
embeddings = pd.read_csv(CORE_GRAPH_DIR / "embedding_posonly.csv", index_col=0)
embeddings = embeddings.apply(np.array, axis=1).to_dict()
embeddings

{'RM0000021': array([ -9.128403, -23.010183]),
 'RM0000392': array([ -8.373507, -23.362133]),
 'RM0090135': array([ -8.059506, -24.006842]),
 'RM0097845': array([ -7.9872026, -22.681086 ]),
 'RM0133233': array([-22.339285 ,  -4.0641565]),
 'RM0134908': array([-10.399134, -11.173418]),
 'RM0135489': array([-15.816205, -26.544724]),
 'RM0135505': array([-17.103632, -28.52467 ]),
 'RM0138805': array([ 1.0584117, -9.715063 ]),
 'RM0000022': array([-11.490021, -26.893806]),
 'RM0000033': array([-11.200818, -26.808294]),
 'RM0000052': array([-12.045052, -26.989618]),
 'RM0000544': array([ -8.571793, -24.507908]),
 'RM0013838': array([-12.870199, -21.693346]),
 'RM0090012': array([-24.328062, -24.391743]),
 'RM0134064': array([-15.400362, -20.855791]),
 'RM0134083': array([-14.312689, -20.598171]),
 'RM0135485': array([-14.17411 , -29.588938]),
 'RM0135487': array([-16.254742, -30.221056]),
 'RM0160764': array([-20.504086, -25.744362]),
 'RM0171045': array([ -9.927366, -28.850132]),
 'RM0000423': array([ -8.11499, -22.10622]),
 'RM0000427': array([ -0.8636983, -29.478262 ]),
 'RM0008618': array([-15.192118, -21.837822]),
 'RM0008639': array([-10.478376, -30.26756 ]),
 'RM0011279': array([ -7.0079613, -25.606522 ]),
 'RM0011593': array([ -6.117737, -39.774426]),
 'RM0025205': array([ -6.7648926, -25.970404 ]),
 'RM0025434': array([ -9.7803335, -28.47146  ]),
 'RM0036777': array([-15.403776, -22.065538]),
 'RM0037707': array([-19.091894, -22.081146]),
 'RM0042554': array([-12.731194, -21.704597]),
 'RM0090021': array([-24.56945 , -24.242458]),
 'RM0134164': array([-21.496277, -25.11126 ]),
 'RM0134192': array([-18.116665, -30.581259]),
 'RM0134725': array([ -6.219842, -39.14026 ]),
 'RM0134757': array([ -6.4516807, -17.951475 ]),
 'RM0135486': array([-15.903669, -31.068295]),
 'RM0135509': array([-20.715506, -25.76271 ]),
 'RM0151646': array([-25.46534 ,  24.518192]),
 'RM0171040': array([-25.129992, -13.09164 ]),
 'RM0171080': array([-26.267054, -12.09847 ]),
 'RM0171094': array([ -1.3484576, -27.574944 ]),
 'RM0171098': array([ -2.9452317, -27.564909 ]),
 'RM0171200': array([ -1.8077282, -19.178041 ]),
 'RM0001077': array([-25.026861, -12.951856]),
 'RM0033561': array([-15.171251, -49.97289 ]),
 'RM0035654': array([-14.223219, -52.29365 ]),
 'RM0044209': array([ -6.4406824, -34.89567  ]),
 'RM0134175': array([-19.591505, -22.304026]),
 'RM0000305': array([-27.839243, -60.050076]),
 'RM0000648': array([-5.771341 , -7.2541037]),
 'RM0000872': array([-5.6056013, -7.124719 ]),
 'RM0001045': array([ -9.276888, -11.976814]),
 'RM0001050': array([-5.4429817, -9.361482 ]),
 'RM0002686': array([-28.818901, -75.057076]),
 'RM0002730': array([-15.488921, -68.95852 ]),
 'RM0002732': array([-17.792406, -67.70665 ]),
 'RM0002776': array([-15.942246, -71.38292 ]),
 'RM0002777': array([-19.866596, -70.69196 ]),
 'RM0002784': array([-22.383158, -70.31844 ]),
 'RM0002807': array([-26.55005 , -47.927948]),
 'RM0002844': array([-32.521385, -77.90171 ]),
 'RM0003152': array([-13.863181, -15.854623]),
 'RM0003180': array([-17.997944, -16.66539 ]),
 'RM0004952': array([-28.749268, -59.804188]),
 'RM0006824': array([-26.903786, -62.471844]),
 'RM0006828': array([-23.192265, -72.61047 ]),
 'RM0006841': array([-28.5415  , -58.432518]),
 'RM0007477': array([-14.896406, -71.11051 ]),
 'RM0007478': array([-27.43673, -58.82182]),
 'RM0008681': array([-30.066992, -18.61857 ]),
 'RM0008718': array([-31.317696, -16.035683]),
 'RM0010652': array([  0.62184846, -35.19378   ]),
 'RM0010684': array([-13.988326, -15.098611]),
 'RM0011394': array([ -7.582011, -10.348126]),
 'RM0011395': array([ -8.403997, -11.501403]),
 'RM0011399': array([-4.0825963, -8.989273 ]),
 'RM0012560': array([-11.541028,  36.710857]),
 'RM0012583': array([-27.34175 , -45.804447]),
 'RM0012621': array([-22.01729 ,  -9.554926]),
 'RM0013471': array([-32.54207, -73.94554]),
 'RM0014885': array([-21.288034, -72.82999 ]),
 'RM0014892': array([-24.893776, -49.48393 ]),
 'RM0014893': array([-20.925993, -63.818066]),
 'RM0014894': array([-20.024845, -68.58166 ]),
 'RM0014927': array([-28.471  , -50.46002]),
 'RM0014999': array([ -6.4089456, -17.254198 ]),
 'RM0015000': array([-11.870329,  -9.623786]),
 'RM0015001': array([ -9.2777 , -12.62239]),
 'RM0015002': array([ -6.861545, -11.860386]),
 'RM0015006': array([ -6.089854, -17.060698]),
 'RM0015038': array([ -6.662317, -17.191065]),
 'RM0015040': array([ -8.755056, -12.417257]),
 'RM0015175': array([-33.989174, -68.39807 ]),
 'RM0015176': array([-29.64115 , -70.376144]),
 'RM0015177': array([-22.430115, -73.11    ]),
 'RM0015178': array([-24.938343, -58.280865]),
 'RM0015179': array([-17.7455 , -71.85736]),
 'RM0015181': array([-19.104567, -70.396385]),
 'RM0015182': array([-24.318285, -55.22849 ]),
 'RM0017415': array([-30.565948, -20.16119 ]),
 'RM0017454': array([-30.426332, -20.055626]),
 'RM0017815': array([ 13.106777, -23.809258]),
 'RM0018237': array([-38.57733, -72.93311]),
 'RM0018672': array([-38.051456, -77.76873 ]),
 'RM0021619': array([-3.2855525, 27.554277 ]),
 'RM0021669': array([-34.78795, -67.70189]),
 'RM0021918': array([-25.475266, -61.64457 ]),
 'RM0023077': array([-38.030224, -76.74857 ]),
 'RM0023084': array([-37.883213, -76.18875 ]),
 'RM0023086': array([-37.060345, -75.472015]),
 'RM0023114': array([-38.82292, -71.91155]),
 'RM0023116': array([-37.336487, -77.8204  ]),
 'RM0023156': array([-33.1905 , -67.67373]),
 'RM0023158': array([-35.597286, -69.9067  ]),
 'RM0023164': array([-34.609344, -70.668015]),
 'RM0023184': array([-19.068638, -74.48601 ]),
 'RM0023191': array([-17.443472, -74.15145 ]),
 'RM0023192': array([-29.121332, -68.99699 ]),
 'RM0023214': array([-20.150434, -72.11081 ]),
 'RM0023215': array([-36.050667, -66.53867 ]),
 'RM0023216': array([-25.646103, -62.464645]),
 'RM0023226': array([-32.177856, -49.801254]),
 'RM0023229': array([-19.651363, -60.90002 ]),
 'RM0023239': array([-32.19256 , -48.919285]),
 'RM0023243': array([-32.354645, -51.606518]),
 'RM0023251': array([-36.080505, -67.27517 ]),
 'RM0023256': array([-31.11374, -67.74816]),
 'RM0023311': array([-18.406475, -63.751186]),
 'RM0023312': array([-28.548332, -60.125587]),
 'RM0023316': array([-13.494283, -69.35432 ]),
 'RM0023321': array([-21.784538, -52.189934]),
 'RM0023322': array([-31.386225, -48.307907]),
 'RM0023326': array([-29.849014, -50.306454]),
 'RM0023345': array([-28.282688, -50.465824]),
 'RM0023349': array([-29.432608, -48.38989 ]),
 'RM0023361': array([-17.325867, -61.011593]),
 'RM0023362': array([-26.457664, -48.985504]),
 'RM0023387': array([-16.966934, -62.417004]),
 'RM0023388': array([-17.940903, -62.342392]),
 'RM0023397': array([-17.1293 , -62.67243]),
 'RM0023398': array([-17.75887 , -62.876278]),
 'RM0023429': array([-17.101507, -62.702213]),
 'RM0023433': array([-26.607359, -59.37349 ]),
 'RM0023441': array([-29.480354, -50.044563]),
 'RM0023467': array([-19.1562, -60.1798]),
 'RM0023470': array([-19.089128, -60.960144]),
 'RM0023473': array([-18.22008 , -60.883778]),
 'RM0023474': array([-18.973429, -60.95102 ]),
 'RM0023501': array([-17.848103, -63.644363]),
 'RM0023505': array([-18.112608, -64.815056]),
 'RM0023506': array([-24.611456, -54.61316 ]),
 'RM0023507': array([-25.641699, -53.93836 ]),
 'RM0023519': array([-27.822805, -57.20122 ]),
 'RM0023520': array([-28.956753, -56.816322]),
 'RM0023542': array([-19.073744, -63.936226]),
 'RM0023548': array([-18.691711, -64.30505 ]),
 'RM0023549': array([-30.600767, -48.44262 ]),
 'RM0023551': array([-29.165606, -50.651203]),
 'RM0023564': array([-23.027988, -56.645996]),
 'RM0023573': array([-26.921892, -49.002106]),
 'RM0023604': array([-21.377335, -52.04665 ]),
 'RM0023605': array([-30.576536, -47.138763]),
 'RM0023614': array([-18.2759  , -60.335426]),
 'RM0023630': array([-22.672697, -54.197594]),
 'RM0023648': array([-24.753084, -52.058426]),
 'RM0023649': array([-23.757256, -53.647972]),
 'RM0023657': array([-22.111103, -53.59008 ]),
 'RM0023660': array([-23.040735, -54.237217]),
 'RM0023674': array([-25.049683, -51.925842]),
 'RM0023681': array([-26.053286, -50.021576]),
 'RM0024126': array([-27.530611, -55.60852 ]),
 'RM0024266': array([-20.309372, -68.87983 ]),
 'RM0024270': array([-26.817007, -57.228405]),
 'RM0025525': array([-15.4240465, -17.04442  ]),
 'RM0027592': array([-38.735233, -75.99601 ]),
 'RM0027634': array([-34.77674, -68.66909]),
 'RM0027656': array([-36.90865, -78.61199]),
 'RM0027677': array([-32.783543, -64.44711 ]),
 'RM0027680': array([-26.659193, -67.33297 ]),
 'RM0027780': array([-18.065992, -62.38379 ]),
 'RM0027800': array([-17.043083, -65.24997 ]),
 'RM0027805': array([-24.113209, -53.780567]),
 'RM0027806': array([-24.786604, -53.152653]),
 'RM0027867': array([-26.570164, -71.526726]),
 'RM0027869': array([-15.699748, -70.669815]),
 'RM0028896': array([-16.464138, -27.003777]),
 'RM0028902': array([-16.390587, -27.244802]),
 'RM0030330': array([-14.001083, -22.400373]),
 'RM0032433': array([-9.530658, 35.840572]),
 'RM0033861': array([-15.23878 , -51.474094]),
 'RM0033929': array([-37.629005, -65.400604]),
 'RM0033952': array([-37.332348, -64.408905]),
 'RM0033977': array([-25.68106, -45.56783]),
 'RM0033995': array([  4.224689, -50.920216]),
 'RM0034180': array([-14.715189, -49.854313]),
 'RM0034254': array([  6.0754104, -50.97424  ]),
 'RM0034278': array([  4.632784, -50.821312]),
 'RM0034314': array([-12.664079, -53.761143]),
 'RM0034432': array([-16.845737, -53.163887]),
 'RM0034458': array([-16.213966, -50.738964]),
 'RM0034465': array([-15.887243, -52.3401  ]),
 'RM0034479': array([  5.3138356, -50.298763 ]),
 'RM0035219': array([-20.46646 , -15.547405]),
 'RM0035650': array([  4.8331304, -51.29354  ]),
 'RM0035676': array([-15.7690115, -52.357807 ]),
 'RM0036732': array([-20.308186, -72.173195]),
 'RM0037210': array([-28.380718, -48.3013  ]),
 'RM0039361': array([-28.986408, -68.1801  ]),
 'RM0040643': array([-29.839981, -75.89352 ]),
 'RM0040698': array([-26.660301, -71.95619 ]),
 'RM0040811': array([-23.458082, -70.206825]),
 'RM0040826': array([-16.756643, -70.346306]),
 'RM0042845': array([-19.213182,  -6.770246]),
 'RM0047158': array([-13.501021, -22.167938]),
 'RM0048598': array([-17.51048 ,  -7.377774]),
 'RM0048630': array([-20.257225,  -8.401295]),
 'RM0050489': array([ 3.295779, 31.067308]),
 'RM0052739': array([-16.51847, -73.77478]),
 'RM0054420': array([-30.533482, -20.095364]),
 'RM0055321': array([-28.751938, -14.838806]),
 'RM0055928': array([-30.43082 , -20.954237]),
 'RM0055968': array([-28.575865, -46.721165]),
 'RM0056115': array([-28.507246, -47.460236]),
 'RM0058966': array([-27.53546, -74.56527]),
 'RM0061147': array([-26.777384, -56.080025]),
 'RM0061223': array([-20.200024, -68.97108 ]),
 'RM0061280': array([-26.598402, -49.784008]),
 'RM0061286': array([-21.332012, -52.58408 ]),
 'RM0061287': array([-21.45705 , -52.500767]),
 'RM0061291': array([-26.151377, -50.768906]),
 'RM0061444': array([-23.154982, -67.40235 ]),
 'RM0061446': array([-20.427755, -65.442955]),
 'RM0061448': array([-15.046271, -69.24747 ]),
 'RM0061695': array([-29.470758, -48.426514]),
 'RM0061898': array([-32.48433, -72.47095]),
 'RM0061899': array([-28.459211, -75.012115]),
 'RM0061900': array([-27.737799, -74.819695]),
 'RM0061901': array([-14.7539215, -69.54784  ]),
 'RM0061902': array([-34.73252, -68.54167]),
 'RM0061903': array([-27.148672, -56.666656]),
 'RM0061904': array([-28.267044, -50.41763 ]),
 'RM0061907': array([-27.97958 , -51.478996]),
 'RM0061909': array([-29.158714, -74.85124 ]),
 'RM0061911': array([-27.24662, -51.72323]),
 'RM0061912': array([-15.95613 , -68.286255]),
 'RM0061914': array([-13.048399, -69.15911 ]),
 'RM0061920': array([-22.712116, -70.79459 ]),
 'RM0061921': array([-28.730373, -63.506454]),
 'RM0061923': array([-24.05479 , -71.666176]),
 'RM0061924': array([-27.238884, -56.444004]),
 'RM0061925': array([-20.231953, -69.485306]),
 'RM0061926': array([-16.70676, -71.19946]),
 'RM0061928': array([-16.85891, -73.45334]),
 'RM0061929': array([-16.731857, -70.74888 ]),
 'RM0061930': array([-26.220749, -59.384304]),
 'RM0061931': array([-14.888071, -71.379654]),
 'RM0061932': array([-23.600681, -63.40988 ]),
 'RM0061947': array([-28.309303, -63.181076]),
 'RM0061948': array([-26.232267, -50.434963]),
 'RM0061949': array([-19.826052, -60.47221 ]),
 'RM0061950': array([-21.940403, -52.025322]),
 'RM0061951': array([-31.302094, -48.788494]),
 'RM0061952': array([-28.671917, -59.789757]),
 'RM0061955': array([-28.628763, -49.648975]),
 'RM0061956': array([-25.725779, -55.124607]),
 'RM0061957': array([-27.245148, -53.68429 ]),
 'RM0061958': array([-31.992567, -49.498573]),
 'RM0061959': array([-29.89288 , -50.835106]),
 'RM0061960': array([-28.788599, -50.67909 ]),
 'RM0064057': array([-37.48397, -71.18386]),
 'RM0064149': array([-30.715052, -48.325745]),
 'RM0064208': array([-37.638695, -71.34217 ]),
 'RM0064249': array([-37.412014, -71.108376]),
 'RM0065603': array([-38.114376, -71.81397 ]),
 'RM0066154': array([-38.17129, -71.07331]),
 'RM0066244': array([-32.288372, -72.891975]),
 'RM0066382': array([-37.751022, -72.93932 ]),
 'RM0066500': array([-33.338646, -76.15302 ]),
 'RM0067279': array([-37.140575, -76.01519 ]),
 'RM0069340': array([-33.682312, -76.25349 ]),
 'RM0069646': array([-31.321707, -74.22736 ]),
 'RM0069688': array([-35.84099, -68.63174]),
 'RM0070196': array([-33.657597, -76.734   ]),
 'RM0071055': array([-37.42872, -73.88392]),
 'RM0071061': array([-37.09936 , -77.741394]),
 'RM0071079': array([-36.769547, -76.01925 ]),
 'RM0071080': array([-35.491066, -74.5085  ]),
 'RM0071082': array([-35.558704, -75.22708 ]),
 'RM0071084': array([-38.947845, -75.696495]),
 'RM0071086': array([-36.39012, -76.37627]),
 'RM0071087': array([-36.18985, -75.86736]),
 'RM0071096': array([-32.504547, -75.30991 ]),
 'RM0071099': array([-35.945717, -78.10069 ]),
 'RM0071100': array([-32.944134, -67.08961 ]),
 'RM0071101': array([-37.36651 , -68.170746]),
 'RM0071104': array([-35.718052, -78.50654 ]),
 'RM0071105': array([-35.275486, -77.703995]),
 'RM0071106': array([-35.234303, -80.13802 ]),
 'RM0071107': array([-34.745922, -78.15864 ]),
 'RM0071108': array([-36.2909 , -78.39209]),
 'RM0071129': array([-35.057457, -80.31689 ]),
 'RM0071133': array([-37.00348, -70.76116]),
 'RM0071135': array([-38.24339, -71.71861]),
 'RM0071137': array([-34.627293, -68.66105 ]),
 'RM0071142': array([-33.60095, -67.82339]),
 'RM0071144': array([-33.654747, -67.890274]),
 'RM0071146': array([-36.47524, -67.75571]),
 'RM0071151': array([-36.433323, -77.06104 ]),
 'RM0071152': array([-30.185621, -73.327965]),
 'RM0071155': array([-36.37091, -77.87163]),
 'RM0071160': array([-32.54901, -78.16611]),
 'RM0071162': array([-30.533924, -65.19425 ]),
 'RM0071183': array([-27.727827, -71.684616]),
 'RM0071184': array([-34.047665, -68.08714 ]),
 'RM0071186': array([-29.266397, -70.82016 ]),
 'RM0071194': array([-29.099459, -68.275536]),
 'RM0071195': array([-32.10914, -67.56791]),
 'RM0071201': array([-35.972923, -70.309875]),
 'RM0071208': array([-33.192097, -64.939896]),
 'RM0071213': array([-32.945736, -64.26104 ]),
 'RM0071214': array([-32.99296 , -50.927082]),
 'RM0071223': array([-36.66453 , -79.435844]),
 'RM0071229': array([-27.698809, -70.0164  ]),
 'RM0071231': array([-27.747944, -70.25218 ]),
 'RM0071238': array([-31.532986, -67.55884 ]),
 'RM0071247': array([-16.430931, -73.84616 ]),
 'RM0071249': array([-28.66482 , -67.631775]),
 'RM0071252': array([-25.464748, -67.3963  ]),
 'RM0071257': array([-34.763943, -63.485016]),
 'RM0071280': array([-25.255518, -75.04845 ]),
 'RM0071282': array([-25.217506, -75.05578 ]),
 'RM0071283': array([-38.78057 , -68.997765]),
 'RM0071288': array([-24.694227, -63.29599 ]),
 'RM0071292': array([-24.601223, -63.4152  ]),
 'RM0071296': array([-20.657894, -64.95664 ]),
 'RM0071301': array([-27.497395, -65.39247 ]),
 'RM0071302': array([-32.046726, -64.21855 ]),
 'RM0071314': array([-28.01391, -64.99479]),
 'RM0071316': array([-32.52312, -51.67587]),
 'RM0071321': array([-25.676666, -65.400406]),
 'RM0071325': array([-32.326817, -51.638325]),
 'RM0071327': array([-33.028633, -69.48861 ]),
 'RM0071349': array([-33.16182, -70.41725]),
 'RM0071353': array([-27.290575, -69.95417 ]),
 'RM0071354': array([-27.452576, -69.95344 ]),
 'RM0071355': array([-27.016773, -70.01708 ]),
 'RM0071366': array([-26.103533, -70.07739 ]),
 'RM0071370': array([-18.924316, -74.19677 ]),
 'RM0071377': array([-25.630283, -68.91377 ]),
 'RM0071380': array([-25.162058, -67.50967 ]),
 'RM0071383': array([-34.71078 , -63.380856]),
 'RM0071399': array([-26.745016, -59.507233]),
 'RM0071424': array([-39.146828, -68.91186 ]),
 'RM0071426': array([-33.95209, -71.6185 ]),
 'RM0071437': array([-21.86554 , -62.187748]),
 'RM0071439': array([-18.449871, -62.48229 ]),
 'RM0071444': array([-18.28654 , -63.497574]),
 'RM0071455': array([-31.18143, -50.67043]),
 'RM0071460': array([-30.794558, -52.61331 ]),
 'RM0071466': array([-13.206026, -69.177635]),
 'RM0071474': array([-25.774551, -47.335213]),
 'RM0071486': array([-22.198162, -61.045944]),
 'RM0071489': array([-20.714487, -62.054554]),
 'RM0071490': array([-16.30101, -65.02689]),
 'RM0071491': array([-18.143797, -61.740334]),
 'RM0071493': array([-18.070538, -61.463085]),
 'RM0071494': array([-16.370037, -64.67335 ]),
 'RM0071495': array([-21.018833, -61.936073]),
 'RM0071496': array([-30.202972, -52.297558]),
 'RM0071498': array([-21.996342, -56.055546]),
 'RM0071515': array([-30.695452, -47.81337 ]),
 'RM0071523': array([-27.693747, -48.79781 ]),
 'RM0071535': array([-25.690416, -48.649815]),
 'RM0071536': array([-27.82781 , -49.272163]),
 'RM0071548': array([-24.359394, -60.941757]),
 'RM0071551': array([-27.175653, -48.19629 ]),
 'RM0071552': array([-26.42887, -51.46889]),
 'RM0071553': array([-22.812433, -54.95208 ]),
 'RM0071559': array([-21.803364, -53.21932 ]),
 'RM0071562': array([-22.76884 , -55.067074]),
 'RM0071563': array([-26.141148, -51.55349 ]),
 'RM0071564': array([-28.735775, -49.816376]),
 'RM0071573': array([-28.296862, -49.621067]),
 'RM0071577': array([-27.772406, -48.848732]),
 'RM0071578': array([-27.402618, -49.157825]),
 'RM0071584': array([-21.391716, -52.259106]),
 'RM0071606': array([-28.621515, -46.467903]),
 'RM0071607': array([-28.30869 , -47.489334]),
 'RM0072544': array([-23.284313, -63.616566]),
 'RM0072552': array([-17.584639, -63.051292]),
 'RM0073742': array([-29.891434, -73.97285 ]),
 'RM0074142': array([-30.590672, -76.469025]),
 'RM0075444': array([-20.452038, -68.59954 ]),
 'RM0075446': array([-22.624681, -70.19084 ]),
 'RM0075447': array([-25.90423 , -75.278145]),
 'RM0075448': array([-27.343008, -72.32965 ]),
 'RM0075449': array([-26.853628, -71.3113  ]),
 'RM0075450': array([-28.401701, -75.01887 ]),
 'RM0075451': array([-28.872423, -75.11141 ]),
 'RM0076422': array([-28.318235, -49.12786 ]),
 'RM0076436': array([-29.503967, -74.15574 ]),
 'RM0076731': array([-17.876339, -70.729385]),
 'RM0076732': array([-27.200872, -74.349335]),
 'RM0076733': array([-22.605047, -72.740486]),
 'RM0076734': array([-22.457378, -71.88634 ]),
 'RM0076735': array([-16.735674, -70.340645]),
 'RM0076736': array([-23.077765, -55.72975 ]),
 'RM0078386': array([-32.794716, -73.719284]),
 'RM0078387': array([-17.747705, -74.05537 ]),
 'RM0078388': array([-21.598299, -72.67673 ]),
 'RM0078389': array([-16.547327, -73.62737 ]),
 'RM0086616': array([-29.184332, -73.22801 ]),
 'RM0086951': array([-30.049969, -66.35047 ]),
 'RM0087046': array([-18.22527, -60.35212]),
 'RM0087120': array([-15.558048, -68.97109 ]),
 'RM0087121': array([-15.149054, -69.3797  ]),
 'RM0087232': array([-25.8267  , -54.710876]),
 'RM0087233': array([-14.210583, -69.54308 ]),
 'RM0087234': array([-26.28355, -56.25779]),
 'RM0090013': array([-39.51151 , -64.753586]),
 'RM0092659': array([-30.252365, -18.545748]),
 'RM0092660': array([-31.309738, -15.803784]),
 'RM0092661': array([-31.335766, -16.096466]),
 'RM0096735': array([-25.237778, -58.107285]),

In [8]:
G, dist = load_core_graph(CORE_GRAPH_DIR, )

# select only nodes that are in the distance matrix (i.e. nodes that are not isolated after removing negative edges)
G = nx.subgraph(G, dist.index)

# remove negative edges
G = G.edge_subgraph([(u,v) for u,v,r in G.edges(data="r") if r>0])

dist

,RM0000021,RM0000392,RM0090135,RM0097845,RM0133233,RM0134908,RM0135489,RM0135505,RM0138805,RM0000022,...,RM0153782,RM0153079,RM0153081,RM0153083,RM0153147,RM0161911,RM0153242,RM0224203,RM0153784,RM0154174
RM0000021,0.000000,0.378429,0.470981,0.418583,0.743224,0.466469,0.720599,0.517737,0.548854,1.276542,...,1.937694,1.643785,1.704059,1.456993,2.666137,2.185107,1.886859,1.818476,1.640611,1.405595
RM0000392,0.378429,0.000000,0.261451,0.221600,0.612044,0.328705,0.399774,0.497072,0.625782,1.229385,...,1.740710,1.535906,1.596180,1.349114,2.414051,1.988124,1.603717,1.535334,1.318003,1.176224
RM0090135,0.470981,0.261451,0.000000,0.441875,0.587624,0.553591,0.546043,0.571209,0.571522,1.086001,...,1.649824,1.507348,1.567622,1.320556,2.544769,2.047378,1.593003,1.533845,1.474753,1.132345
RM0097845,0.418583,0.221600,0.441875,0.000000,0.561150,0.188085,0.367810,0.521535,0.538548,1.103893,...,1.519111,1.400465,1.450494,1.213673,2.278610,1.766524,1.468276,1.399893,1.222028,0.996132
RM0133233,0.743224,0.612044,0.587624,0.561150,0.000000,0.566448,0.554518,0.510065,0.522295,1.067293,...,1.378009,1.386929,1.447203,1.200137,2.162928,1.766322,1.445356,1.376973,0.907539,0.973509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RM0161911,2.185107,1.988124,2.047378,1.766524,1.766322,1.917454,1.923068,1.955272,1.878724,2.516613,...,2.816782,2.193620,2.113322,2.006828,3.458029,0.000000,2.519219,2.505553,2.511956,2.243189
RM0153242,1.886859,1.603717,1.593003,1.468276,1.445356,1.458378,1.523541,1.502974,1.476979,1.970440,...,2.203899,1.872093,1.932368,1.685302,2.736418,2.519219,0.000000,1.854629,1.972182,1.465434
RM0224203,1.818476,1.535334,1.533845,1.399893,1.376973,1.389995,1.464382,1.439166,1.408596,1.902057,...,2.138452,1.795483,1.855758,1.608692,2.797170,2.505553,1.854629,0.000000,1.901098,1.592447
RM0153784,1.640611,1.318003,1.474753,1.222028,0.907539,1.313361,1.174238,1.394534,1.207746,1.947723,...,1.584094,1.709964,1.740108,1.507245,2.488834,2.511956,1.972182,1.901098,0.000000,1.525166
RM0154174,1.405595,1.176224,1.132345,0.996132,0.973509,0.939126,0.776450,0.975423,0.866484,1.441021,...,1.680570,1.336840,1.447164,1.200098,2.559039,2.243189,1.465434,1.592447,1.525166,0.000000

In [9]:
# G number of connected components
len([None for component in nx.connected_components(G)])

1

In [10]:
SUPER_CLASSES = set([G.nodes()[node]["super_class"] for node in G.nodes() if G.nodes[node]["super_class"]])
SUPER_CLASS_ENCODING = {super_class: i for i, super_class in enumerate(SUPER_CLASSES)}
SUPER_CLASS_ENCODING

{'Organic oxygen compounds': 0,
 'Alkaloids': 1,
 'Prenol Lipids': 2,
 'Organic acids': 3,
 'Sterol Lipids': 4,
 'Carbohydrates': 5,
 'Glycerophospholipids': 6,
 'Inorganic compounds': 7,
 'Organosulfur compounds': 8,
 'Lignans': 9,
 'Glycerolipids': 10,
 'Organic nitrogen compounds': 11,
 'Benzenoids': 12,
 'Fatty Acyls': 13,
 'Nucleic acids': 14,
 'Organohalogen compounds': 15,
 'Organoheterocyclic compounds': 16,
 'Sphingolipids': 17,
 'Polyketides': 18}

In [11]:
G.nodes()["RM0001239"]

{'refmet_name': 'PE 34:2',
 'super_class': 'Glycerophospholipids',
 'main_class': 'Glycerophosphoethanolamines',
 'sub_class': 'PE',
 'formula': 'C39H74NO8P',
 'exactmass': 715.515207,
 'pubchem_cid': nan,
 'chebi_id': 71721.0,
 'hmdb_id': nan,
 'lipidmaps_id': nan,
 'kegg_id': nan,
 'inchi_key': nan}

In [12]:
def annotate_metabolites(refmet_ids, associations=all_associations):
    """
    Return the attributes of a node in the graph.
    """
    z = np.array([metabolite_association(refmet_id, associations=associations) for refmet_id in refmet_ids])
    return {
        "z": z,
        "super_class": np.array([G.nodes()[refmet_id]["super_class"] for refmet_id in refmet_ids]),
        "exactmass": np.array([G.nodes()[refmet_id]["exactmass"] for refmet_id in refmet_ids]),
        
    }
annotate_metabolites(["RM0001239", "RM0097845", "RM0154019"])

{'z': array([0.11712889,        nan, 0.09180745]),
 'super_class': array(['Glycerophospholipids', 'Glycerophospholipids', 'Fatty Acyls'],
       dtype='<U20'),
 'exactmass': array([715.515207, 785.593457, 275.173274])}

In [37]:
def get_metabolites_features(refmet_ids, associations=all_associations):
    """
    Return numerical representation of a metabolite's attributes
    """
    attrs = annotate_metabolites(refmet_ids, associations=associations)
    super_class_ohe = np.zeros((len(refmet_ids), len(SUPER_CLASSES)))
    for i, super_class in enumerate(attrs["super_class"]):
        super_class_ohe[i, SUPER_CLASS_ENCODING[super_class]] = 1

    return np.concatenate([
        super_class_ohe,
        attrs["exactmass"].reshape(-1, 1),
        attrs["z"].reshape(-1, 1)
    ], axis=1)

get_metabolites_features(["RM0001239", "RM0097845", "RM0154019"], associations=associations_purged_from("ST000916"))

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.15515207e+02,
        1.50266538e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.85593457e+02,
                   nan],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.75173274e+02,
        9.18074518e-02]])

In [36]:
def get_graph_features(associations=all_associations):
    return get_metabolites_features(np.array(G.nodes()), associations=associations)

In [44]:
def propagate(G, y, precision, alpha, nodelist):
    W = nx.to_scipy_sparse_array(G, nodelist=nodelist, weight="weight", format="csr")
    L = diags(W.sum(axis=1).A1) - W          # sparse Laplacian
    S = diags(precision)                      # 0 for untested, 1/SE^2 for tested
    A = S + alpha * L
    f, info = cg(A, S @ y)                    # conjugate gradient, not explicit inverse
    return f

/tmp/ipykernel_2145449/1779235639.py:9: RuntimeWarning: invalid value encountered in scalar divide
  z = (w*z).sum()/w.sum()
/tmp/ipykernel_2145449/1779235639.py:9: RuntimeWarning: invalid value encountered in scalar divide
  z = (w*z).sum()/w.sum()

AttributeError: 'numpy.ndarray' object has no attribute 'A1'

In [45]:
nx.to_scipy_sparse_array(G, weight="weight", format="csr")

<Compressed Sparse Row sparse array of dtype 'float64'
	with 1586130 stored elements and shape (4429, 4429)>